kind: pipeline
type: docker
name: Build

trigger:
  branch:
    - main
  event:
    include:
      - push
steps:
- name: Build docker image & push to repository
  image: plugins/docker
  environment:
    PNKL_VAULT_TOKEN:
      from_secret: PNKL_VAULT_TOKEN 
    GITHUB_TOKEN:
      from_secret: GITHUB_TOKEN
    GO_ENVIRONMENT:
      from_secret: GO_ENVIRONMENT
    LOG_LEVEL:
      from_secret: LOG_LEVEL      
    BUILD_VERSION: ${DRONE_COMMIT_SHA:0:7}
  settings:
    registry: registry.punk.link
    repo: registry.punk.link/spotify-service
    tags:
      - ${DRONE_COMMIT_SHA:0:7}
      - ${DRONE_COMMIT_BRANCH}
    force_tag: true
    use_cache: true
    username:
      from_secret: DOCKER_LOGIN
    password:
      from_secret: DOCKER_PASSWORD
    build_args_from_env:
      - PNKL_VAULT_TOKEN
      - GITHUB_TOKEN
      - BUILD_VERSION
      - GO_ENVIRONMENT
      - LOG_LEVEL

- name: Deploy to DEV
  image: pelotech/drone-helm3
  settings:
    mode: upgrade
    chart: ./Helm/
    release: ss-dev
    values_files: ["Helm/values_dev.yaml"]
    namespace: dev
    skip_tls_verify: true
    wait_for_upgrade: true
    values: image.tag=${DRONE_COMMIT_SHA:0:7}
  environment:
    KUBE_API_SERVER:
      from_secret: KUBERNETES_DEV_API
    KUBE_TOKEN:
      from_secret: KUBERNETES_DEV_TOKEN      
      
- name: send telegram notification
  image: appleboy/drone-telegram
  settings:
    token: 
      from_secret: TELEGRAM_TOKEN
    to: 
      from_secret: TELEGRAM_GROUP_ID
    message: >
      {{#success build.status}}
        ✅ Build {{build.number}} `{{ build.event }}` of `{{repo.name}}` succeeded. Commit by {{commit.author}} on `{{commit.branch}}` ``` {{commit.message}} ``` {{ build.link }}
      {{else}}
        ❌ Build {{build.number}} `{{ build.event }}` of `{{repo.name}}` failed. Commit by {{commit.author}} on `{{commit.branch}}` ``` {{commit.message}} ``` {{ build.link }}
      {{/success}}
  when:
    status: [success, failure]  
- name: discord-notify
  image: brazildatacube/bdc-drone-discord
  settings:
    webhook:
      from_secret: discord_webhook
  when:
    status: [success, failure]    
